params:
  diff_env:
    name: humanoid
    env_name: HumanoidEnv

  config:
    _target_: dmanip.envs.HumanoidEnv
    render: ${render}
    device: ${general.device}
    num_envs: 64
    no_grad: ??? # decided based on algorithm
    stochastic_init: True
    seed: ${general.seed}
    episode_length: 1000
    MM_caching_frequency: 48

shac:
  actor_lr: 2e-3
  critic_lr: 5e-4
  max_epochs: 5000
  target_critic_alpha: 0.995
  actor_mlp:
    units: [256, 128]
  critic_mlp:
    units: [256, 128]

ppo:
  max_epochs: 2000
  minibatch_size: 8192
  num_actors: 1024
  steps_num: 32
  actor_mlp:
    units: [256, 128, 64]
  critic_mlp:
    units: [256, 128, 64]
